version: '3.8'
services:
  backend:
    build: .
    network_mode: "host"
    environment:
      - DATABASE_URL=postgresql://postgres:JDLifestylepostgresPassword@localhost:5432/postgres
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=JDLifestyle.store.secret
      - SALT_ROUNDS=10
      - FRONTEND_URL=https://www.jdlifestyle.store/
    depends_on:
      - db
    restart: always
    volumes:
      - ./public/uploads:/usr/src/app/public/uploads
  
  db:
    image: postgres:14
    network_mode: "host"
    environment:
      - POSTGRES_PASSWORD=JDLifestylepostgresPassword
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: